- name: Get home directory for {{ shell_user }}
  ansible.builtin.set_fact:
    qubinode_kvmhost_setup_current_user_homedir: "{{ lookup('env', 'HOME') }}"
  become: true
  become_user: "{{ shell_user }}"
  when: shell_user != 'root'

- name: Set root user homedir
  ansible.builtin.set_fact:
    qubinode_kvmhost_setup_current_user_homedir: /root
  when: shell_user == 'root'

- name: User shell configuration files
  vars:
    user_homedir: "{{ qubinode_kvmhost_setup_current_user_homedir }}"
  ansible.builtin.include_tasks: user_shell_configs.yml
