# GPG Key Verification Tasks for ADR-0001 Compliance
# Enhanced security compliance with automatic key verification

- name: Ensure DNF GPG key verification is enabled globally
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^gpgcheck=
    line: gpgcheck=1
    backup: true
  become: true
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Ensure DNF repo GPG key verification is enabled globally
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^repo_gpgcheck=
    line: repo_gpgcheck=1
    backup: true
  become: true
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Ensure DNF local package GPG verification is enabled
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^localpkg_gpgcheck=
    line: localpkg_gpgcheck=1
    backup: true
  become: true
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Verify GPG keys are properly imported for RHEL/Rocky repositories
  ansible.builtin.command: >
    rpm -qa gpg-pubkey* --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
  register: imported_gpg_keys
  changed_when: false
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Display imported GPG keys for verification
  ansible.builtin.debug:
    msg: |
      Imported GPG Keys:
      {{ imported_gpg_keys.stdout }}
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Verify DNF configuration compliance
  ansible.builtin.command: dnf config-manager --dump
  register: dnf_config_dump
  changed_when: false
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Assert GPG checking is enabled
  ansible.builtin.assert:
    that:
      - "'gpgcheck = 1' in dnf_config_dump.stdout or 'gpgcheck = True' in dnf_config_dump.stdout"
    fail_msg: GPG checking is not properly enabled in DNF configuration
    success_msg: GPG checking is properly enabled - ADR-0001 compliance verified
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Test EPEL GPG key verification with a safe package query
  ansible.builtin.command: dnf info epel-release
  register: epel_info_check
  changed_when: false
  failed_when: false
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Check if EPEL repository is available and configured
  ansible.builtin.command: dnf repolist --enabled
  register: enabled_repos_check
  changed_when: false
  failed_when: false
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Verify EPEL repository GPG signature validation
  ansible.builtin.assert:
    that:
      - epel_info_check.rc == 0
    fail_msg: EPEL repository GPG verification failed
    success_msg: EPEL repository GPG verification successful
  when:
    - epel_info_check is defined
    - "'epel' in enabled_repos_check.stdout | lower"
    - not (ansible_virtualization_type | default('') in ['container', 'docker', 'podman'])
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Skip EPEL GPG verification in container environments
  ansible.builtin.debug:
    msg: Skipping EPEL GPG verification - container environment detected or EPEL not configured
  when:
    - ansible_virtualization_type | default('') in ['container', 'docker', 'podman'] or "'epel' not in
      enabled_repos_check.stdout | lower"
  tags:
    - security
    - gpg_verification
    - adr_0001

- name: Create GPG verification status report
  ansible.builtin.template:
    src: gpg_verification_report.j2
    dest: /var/log/ansible-gpg-verification-{{ ansible_date_time.epoch }}.log
    mode: "0644"
  become: true
  tags:
    - security
    - gpg_verification
    - adr_0001
    - reporting
