---
# =============================================================================
# MODULAR ROLES CONVERGE PLAYBOOK
# =============================================================================
# Tests all modular roles with variable validation framework integration

- name: Converge Modular Roles
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Enable testing mode for CI/CD
    testing_mode: true
    cicd_test: true
    
    # Variable validation framework settings
    validation_scope: "all_roles"
    enable_drift_detection: true
    save_validation_report: false
    
    # Base configuration (kvmhost_base role)
    supported_os_families:
      - RedHat
      - CentOS
      - Rocky
      - AlmaLinux
    supported_major_versions:
      - "8"
      - "9"
      - "10"
    base_packages_common:
      - curl
      - wget
      - git
      - vim
      - htop
    base_packages_rhel_family:
      - dnf-utils
      - NetworkManager
      - firewalld
    enable_epel: true
    epel_installation_method: "dnf_module"  # ADR-0001 compliant
    base_services_enabled:
      - NetworkManager
      - firewalld
    
    # Networking configuration (kvmhost_networking role)
    kvmhost_bridge_device: "virbr0"
    dns_forwarder: "8.8.8.8"
    domain: "test.local"
    enable_firewall: true
    firewall_zones:
      - public
    libvirt_host_networks:
      - name: "default"
        mode: "bridge"
        bridge_device: "virbr0"
        forward_mode: "bridge"
        dhcp:
          enabled: true
          start: "192.168.122.100"
          end: "192.168.122.200"
      - name: "isolated"
        mode: "isolated"
        bridge_device: "virbr1"
    
    # Storage configuration (kvmhost_storage role)
    kvm_host_libvirt_dir: "/var/lib/libvirt"
    libvirt_host_storage_pools:
      - name: "default"
        type: "dir"
        path: "/var/lib/libvirt/images"
        autostart: true
        target:
          path: "/var/lib/libvirt/images"
          permissions:
            mode: "0711"
            owner: "root"
            group: "root"
      - name: "test-pool"
        type: "dir"
        path: "/var/lib/libvirt/test-images"
        autostart: false
    storage_performance_tuning:
      enable_io_scheduler: true
      io_scheduler: "mq-deadline"
      enable_transparent_hugepages: false
    
    # Cockpit configuration (kvmhost_cockpit role)
    enable_cockpit: true
    kvmhost_cockpit_port: 9090
    kvmhost_cockpit_ssl_enabled: true
    cockpit_packages:
      - cockpit
      - cockpit-machines
      - cockpit-networkmanager
    cockpit_modules:
      - machines
      - networkmanager
      - system
    cockpit_firewall_zone: "public"
    cockpit_auth_methods:
      - password
    
    # User configuration (kvmhost_user_config role)
    admin_user: "testuser"
    configure_shell: true
    enable_libvirt_admin_user: true
    user_shell_configs:
      enable_starship: false  # Disable for testing performance
      enable_bash_completion: true
      custom_aliases:
        ll: "ls -la"
        grep: "grep --color=auto"
      environment_variables:
        EDITOR: "vim"
        HISTSIZE: "10000"
      vim_configuration:
        enable_syntax_highlighting: true
        enable_line_numbers: true
        tab_size: 4
    ssh_configuration:
      enable_ssh_key_auth: true
      disable_password_auth: false  # Keep enabled for testing
      ssh_port: 22
      allowed_users:
        - testuser
        - root
    user_groups:
      - libvirt
      - wheel
    sudo_configuration:
      enable_passwordless_sudo: true
      sudo_timeout: 15

  tasks:
    - name: "=== Variable Validation Framework Test ==="
      block:
        - name: Run comprehensive variable validation
          ansible.builtin.include_tasks: "{{ playbook_dir }}/validation/schema_validation.yml"
          vars:
            validation_scope: "all_roles"
          tags:
            - validation
            - schema_validation

    - name: "=== Base Role Deployment ==="
      block:
        - name: Apply kvmhost_base role
          ansible.builtin.include_role:
            name: kvmhost_base
          tags:
            - base
            - modular_roles

    - name: "=== Networking Role Deployment ==="
      block:
        - name: Apply kvmhost_networking role
          ansible.builtin.include_role:
            name: kvmhost_networking
          tags:
            - networking
            - modular_roles

    - name: "=== Storage Role Deployment ==="
      block:
        - name: Apply kvmhost_storage role
          ansible.builtin.include_role:
            name: kvmhost_storage
          tags:
            - storage
            - modular_roles

    - name: "=== Libvirt Role Deployment ==="
      block:
        - name: Apply kvmhost_libvirt role
          ansible.builtin.include_role:
            name: kvmhost_libvirt
          tags:
            - libvirt
            - modular_roles

    - name: "=== Cockpit Role Deployment ==="
      block:
        - name: Apply kvmhost_cockpit role
          ansible.builtin.include_role:
            name: kvmhost_cockpit
          tags:
            - cockpit
            - modular_roles

    - name: "=== User Configuration Role Deployment ==="
      block:
        - name: Create test user for validation
          ansible.builtin.user:
            name: "{{ admin_user }}"
            shell: /bin/bash
            create_home: true
            groups: wheel
            append: true
          
        - name: Apply kvmhost_user_config role
          ansible.builtin.include_role:
            name: kvmhost_user_config
          tags:
            - user_config
            - modular_roles

    - name: "=== Cross-Role Integration Test ==="
      block:
        - name: Verify libvirt connectivity
          ansible.builtin.command: virsh list --all
          register: virsh_test
          changed_when: false
          
        - name: Test network configuration
          ansible.builtin.command: virsh net-list --all
          register: net_test
          changed_when: false
          
        - name: Test storage pool configuration
          ansible.builtin.command: virsh pool-list --all
          register: pool_test
          changed_when: false
          
        - name: Display integration test results
          ansible.builtin.debug:
            msg: |
              Cross-Role Integration Test Results:
              ===================================
              libvirt connectivity: {{ 'PASS' if virsh_test.rc == 0 else 'FAIL' }}
              Network configuration: {{ 'PASS' if 'default' in net_test.stdout else 'FAIL' }}
              Storage configuration: {{ 'PASS' if 'default' in pool_test.stdout else 'FAIL' }}
              
              All modular roles deployed successfully! ✅
