# =============================================================================
# SSH CONFIG VALIDATION HELPER
# =============================================================================
# Validates SSH configuration

- name: Validate SSH port range
  ansible.builtin.set_fact:
    validation_errors: "{{ validation_errors + [ssh_port_error_msg] }}"
  vars:
    ssh_port_error_msg: "kvmhost_user_config validation error: SSH port '{{ kvmhost_user_config_vars.ssh_configuration.ssh_port
      }}' must be between 1024 and 65535"
  when:
    - kvmhost_user_config_vars.ssh_configuration.ssh_port is defined
    - (kvmhost_user_config_vars.ssh_configuration.ssh_port | int < 1024 or 
      kvmhost_user_config_vars.ssh_configuration.ssh_port | int > 65535)

- name: Validate allowed users pattern
  ansible.builtin.set_fact:
    validation_errors: "{{ validation_errors + [allowed_user_error_msg] }}"
  vars:
    allowed_user_error_msg: "kvmhost_user_config validation error: Allowed user '{{ item }}' does not match naming pattern"
  when:
    - kvmhost_user_config_vars.ssh_configuration.allowed_users is defined
    - not (item | regex_search('^[a-zA-Z][a-zA-Z0-9_-]*$'))
  loop: "{{ kvmhost_user_config_vars.ssh_configuration.allowed_users }}"
