# kvmhost_networking role meta information
# Handles network bridge configuration and validation

galaxy_info:
  author: Qubinode Project
  description: KVM host network bridge configuration and validation
  company: Red Hat
  license: GPL-3.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "all"
        - "all"
        - "all"
    - name: Rocky
      versions:
        - "all"
        - "all"
    - name: AlmaLinux
      versions:
        - "all"
        - "all"

dependencies:
  - role: kvmhost_base

collections:
  - ansible.posix
  - community.general
