# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: tosin2013
name: qubinode_kvmhost_setup_collection
version: "0.9.2"
readme: README.md
authors:
  - Tosin Akinosho (github.com/tosin2013)
  - Rodrique Heron (github.com/flyemsafe)
description: This Ansible Collection for Virtual Machines Setup provides a set of roles for configuring and managing KVM
  hosts in baremetal servers using RHEL-based Linux operating systems.
license_file: LICENSE
tags:
  # tags so people can search for collections https://galaxy.ansible.com/search
  # tags are all lower-case, no spaces, no dashes.
  - kvm
  - libvirt
  - kvmhost
  - linux
repository: https://github.com/Qubinode/qubinode_kvmhost_setup_collection
#documentation: https://github.com/Qubinode/qubinode_kvmhost_setup_collection/tree/main/docs
homepage: https://github.com/Qubinode/qubinode_kvmhost_setup_collection
issues: https://github.com/Qubinode/qubinode_kvmhost_setup_collection/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
