---
- name: Test Container Detection Logic
  hosts: rocky-9,alma-9
  become: true
  gather_facts: true
  tasks:
    - name: Include advanced container detection task only
      ansible.builtin.include_tasks: roles/kvmhost_setup/tasks/performance_optimization.yml
      tags: performance
