# =============================================================================
# VARIABLE VALIDATION FRAMEWORK TEST PLAYBOOK
# =============================================================================
# Tests the schema validation framework with sample configurations

- name: Test Variable Validation Framework
  hosts: localhost
  gather_facts: true
  vars:
    # Test variables for validation framework
    validation_scope: "all_roles"
    enable_drift_detection: true
    save_validation_report: false
    # Sample kvmhost_base variables
    cicd_test: false
    testing_mode: false
    supported_os_families:
      - RedHat
      - CentOS
      - Rocky
      - AlmaLinux
    supported_major_versions:
      - "8"
      - "9"
      - "10"
    base_packages_common:
      - curl
      - wget
      - git
      - vim
    base_packages_rhel_family:
      - dnf-utils
      - NetworkManager
    enable_epel: true
    epel_installation_method: "dnf_module"  # ADR-0001 compliant
    base_services_enabled:
      - NetworkManager
      - firewalld
    # Sample kvmhost_networking variables
    kvmhost_bridge_device: "virbr0"
    dns_forwarder: "8.8.8.8"
    domain: "example.local"
    libvirt_host_networks:
      - name: "default"
        mode: "bridge"
        bridge_device: "virbr0"
        forward_mode: "bridge"
        dhcp:
          enabled: true
          start: "192.168.122.100"
          end: "192.168.122.200"
    # Sample kvmhost_storage variables
    kvm_host_libvirt_dir: "/var/lib/libvirt"
    libvirt_host_storage_pools:
      - name: "default"
        type: "dir"
        path: "/var/lib/libvirt/images"
        autostart: true
    # Sample kvmhost_cockpit variables
    enable_cockpit: true
    kvmhost_cockpit_port: 9090
    kvmhost_cockpit_ssl_enabled: true
    cockpit_packages:
      - cockpit
      - cockpit-machines
    cockpit_modules:
      - machines
      - networkmanager
    # Sample kvmhost_user_config variables
    admin_user: "qubinode"
    configure_shell: true
    enable_libvirt_admin_user: true
    user_shell_configs:
      enable_starship: true
      enable_bash_completion: true
      vim_configuration:
        enable_syntax_highlighting: true
        enable_line_numbers: true
        tab_size: 4
    user_groups:
      - libvirt
      - wheel

  tasks:
    - name: Display test configuration
      ansible.builtin.debug:
        msg: |
          Testing Variable Validation Framework
          =====================================
          Validation Scope: {{ validation_scope }}
          Drift Detection: {{ enable_drift_detection }}
          OS Family: {{ ansible_os_family | default('unknown') }}
          Distribution: {{ ansible_distribution | default('unknown') }}

    - name: Run variable validation framework
      ansible.builtin.include_tasks: validation/schema_validation.yml
    - name: Display validation results summary
      ansible.builtin.debug:
        msg: |
          Validation Framework Test Results
          =================================
          Errors: {{ validation_errors | default([]) | length }}
          Warnings: {{ validation_warnings | default([]) | length }}
          Status: {{ 'PASSED' if validation_errors | default([]) | length == 0 else 'FAILED' }}
          {% if validation_errors | default([]) | length > 0 %}
          Errors:
          {% for error in validation_errors %}
          - {{ error }}
          {% endfor %}
          {% endif %}
          {% if validation_warnings | default([]) | length > 0 %}
          Warnings:
          {% for warning in validation_warnings %}
          - {{ warning }}
          {% endfor %}
          {% endif %}
