---
- name: Include shell configuration tasks
  ansible.builtin.include_tasks: shell.yml
  when: configure_shell | bool

- name: Include cockpit configuration tasks
  ansible.builtin.include_tasks: cockpit.yml
  when: enable_cockpit | bool

- name: Include remote access configuration tasks
  ansible.builtin.include_tasks: remote.yml
  when:
    - enable_cockpit | bool
    - lookup('env', 'GUID', default='') != ""
