---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  # Podman driver for local development
  name: podman
  options:
    podman_binary: /usr/bin/podman
    podman_extra_args: --log-level=info
    ansible_connection_options:
      ansible_podman_executable: /usr/bin/podman

platforms:
  # CentOS Stream 10 - Latest upstream for RHEL 10
  - name: centos-stream10-test
    image: quay.io/centos/centos:stream10
    dockerfile: Dockerfile.rhel
    pre_build_image: false
    systemd: always
    command: "/usr/sbin/init"
    # Security-enhanced configuration per ADR-0012 (no privileged containers)
    capabilities:
      - SYS_ADMIN
    groups:
      - rhel10_compatible
      - centos_stream
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible_user: root
    ansible_connection: podman

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: "1"
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      host_key_checking: false
      deprecation_warnings: false
      roles_path: "../../roles"
    ssh_connection:
      pipelining: true
  inventory:
    links:
      hosts: ../../inventories/molecule/hosts
      group_vars: ../../inventories/molecule/group_vars/
  playbooks:
    converge: converge.yml
    verify: verify.yml

lint: |
  set -e
  yamllint .
  ansible-lint roles/kvmhost_setup/ --exclude .github/

verifier:
  name: testinfra
  options:
    verbose: true

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
