# =============================================================================
# LIBVIRT NETWORK CREATION
# =============================================================================
# Create individual libvirt network

- name: Display network creation details
  ansible.builtin.debug:
    msg:
      - "Creating network: {{ network_item.name }}"
      - "Mode: {{ network_item.mode | default('bridge') }}"
      - "Bridge: {{ network_item.bridge_name | default('N/A') }}"
  when: kvmhost_libvirt_debug_enabled | default(false)

- name: Check if network already exists
  ansible.builtin.command: "virsh net-info {{ network_item.name }}"
  register: network_exists_check
  changed_when: false
  failed_when: false
  become: true

- name: Create bridge mode network
  community.libvirt.virt_net:
    command: define
    name: "{{ network_item.name }}"
    xml: '{{ lookup("template", "libvirt_net_bridge.xml.j2") }}'
  become: true
  when:
    - network_exists_check.rc != 0
    - network_item.mode | default('bridge') == 'bridge'
  register: bridge_network_created

- name: Create NAT mode network
  community.libvirt.virt_net:
    command: define
    name: "{{ network_item.name }}"
    xml: '{{ lookup("template", "libvirt_net_nat.xml.j2") }}'
  become: true
  when:
    - network_exists_check.rc != 0
    - network_item.mode | default('bridge') == 'nat'
  register: nat_network_created

- name: Create isolated mode network
  community.libvirt.virt_net:
    command: define
    name: "{{ network_item.name }}"
    xml: '{{ lookup("template", "libvirt_net_isolated.xml.j2") }}'
  become: true
  when:
    - network_exists_check.rc != 0
    - network_item.mode | default('bridge') == 'isolated'
  register: isolated_network_created

- name: Start libvirt network
  community.libvirt.virt_net:
    state: active
    name: "{{ network_item.name }}"
  become: true
  register: network_started

- name: Configure network autostart
  community.libvirt.virt_net:
    autostart: "{{ network_item.autostart | default(true) }}"
    name: "{{ network_item.name }}"
  become: true
  when: network_item.autostart is defined

- name: Display network creation result
  ansible.builtin.debug:
    msg: "Network {{ network_item.name }} configured successfully"
  when:
    - kvmhost_libvirt_debug_enabled | default(false)
    - (bridge_network_created is defined and bridge_network_created.changed) or (nat_network_created is defined and
      nat_network_created.changed) or (isolated_network_created is defined and isolated_network_created.changed) or
      network_exists_check.rc == 0
