# =============================================================================
# LVM SETUP TASKS
# =============================================================================
# Configure LVM for advanced storage management

- name: Display LVM configuration
  ansible.builtin.debug:
    msg:
      - "Configuring LVM storage"
      - "Device: /dev/{{ kvmhost_storage_lvm_device }}"
      - "Volume Group: {{ kvmhost_storage_lvm_vg_name }}"
      - "Volumes: {{ kvmhost_storage_lvm_volumes | selectattr('enabled') | list | length }}"
  when: kvmhost_storage_debug_enabled | default(false)

- name: Create physical volume
  community.general.lvg:
    vg: "{{ kvmhost_storage_lvm_vg_name }}"
    pvs: "/dev/{{ kvmhost_storage_lvm_device }}"
    force: "{{ kvmhost_storage_lvm_force_create }}"
    state: present
  become: true
  register: vg_creation_result

- name: Display volume group creation result
  ansible.builtin.debug:
    msg: "Volume group {{ kvmhost_storage_lvm_vg_name }} {{ 'created' if vg_creation_result.changed else 'already exists'
      }}"
  when: kvmhost_storage_debug_enabled | default(false)

- name: Create logical volumes
  community.general.lvol:
    vg: "{{ kvmhost_storage_lvm_vg_name }}"
    lv: "lv_{{ item.name }}"
    size: "{{ item.size }}"
    state: present
  loop: "{{ kvmhost_storage_lvm_volumes }}"
  when: item.enabled | default(true)
  become: true
  register: lv_creation_result

- name: Create filesystems on logical volumes
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "/dev/mapper/{{ kvmhost_storage_lvm_vg_name }}-lv_{{ item.name }}"
    opts: "-L {{ item.name }}"
    force: false
  loop: "{{ kvmhost_storage_lvm_volumes }}"
  when: item.enabled | default(true)
  become: true
  register: fs_creation_result

- name: Create mount point directories
  ansible.builtin.ansible.builtin.file:
    path: "{{ item.mount_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop: "{{ kvmhost_storage_lvm_volumes }}"
  when: item.enabled | default(true)
  become: true

- name: Configure mount points in fstab and mount
  ansible.posix.ansible.posix.mount:
    name: "{{ item.mount_dir }}"
    src: "/dev/mapper/{{ kvmhost_storage_lvm_vg_name }}-lv_{{ item.name }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ kvmhost_storage_mount_options[item.fstype] | default('defaults') }}"
    dump: 0
    passno: 0
    state: mounted
  loop: "{{ kvmhost_storage_lvm_volumes }}"
  when: item.enabled | default(true)
  become: true
  register: mount_result

- name: Set correct ownership for libvirt directories
  ansible.builtin.ansible.builtin.file:
    path: "{{ item.mount_dir }}"
    owner: root
    group: root
    mode: "0711"
    recurse: false
  loop: "{{ kvmhost_storage_lvm_volumes }}"
  when:
    - item.enabled | default(true)
    - "'libvirt' in item.mount_dir"
  become: true

- name: Display LVM setup completion
  ansible.builtin.debug:
    msg:
      - "LVM configuration completed"
      - "Mounted volumes: {{ kvmhost_storage_lvm_volumes | selectattr('enabled') | list | map(attribute='mount_dir') | join(',
        ') }}"
  when: kvmhost_storage_debug_enabled | default(false)
