---
# =============================================================================
# KVMHOST STORAGE ROLE - MAIN TASKS
# =============================================================================
# Advanced storage management for KVM hosts including LVM, performance
# optimization, and monitoring following ADR-0002 modular architecture.

- name: Display storage configuration summary
  ansible.builtin.debug:
    msg:
      - === KVM Host Storage Configuration ===
      - "Storage enabled: {{ kvmhost_storage_enabled }}"
      - "LVM enabled: {{ kvmhost_storage_lvm_enabled }}"
      - "Advanced pools: {{ kvmhost_storage_pools_enabled }}"
      - "Performance optimization: {{ kvmhost_storage_performance_enabled }}"
      - "Monitoring: {{ kvmhost_storage_monitoring_enabled }}"
  when: kvmhost_storage_debug_enabled | default(false)

- name: Include storage validation
  ansible.builtin.include_tasks: validation.yml
  when: kvmhost_storage_validation_enabled | default(true)

- name: Include LVM configuration
  ansible.builtin.include_tasks: lvm_setup.yml
  when:
    - kvmhost_storage_enabled | default(true)
    - kvmhost_storage_lvm_enabled | default(false)
    - kvmhost_storage_lvm_device | length > 0

- name: Include advanced storage pools
  ansible.builtin.include_tasks: advanced_pools.yml
  when:
    - kvmhost_storage_enabled | default(true)
    - kvmhost_storage_pools_enabled | default(true)

- name: Include performance optimization
  ansible.builtin.include_tasks: performance.yml
  when:
    - kvmhost_storage_enabled | default(true)
    - kvmhost_storage_performance_enabled | default(true)

- name: Include storage monitoring
  ansible.builtin.include_tasks: monitoring.yml
  when:
    - kvmhost_storage_enabled | default(true)
    - kvmhost_storage_monitoring_enabled | default(true)

- name: Include backup and snapshot configuration
  ansible.builtin.include_tasks: backup.yml
  when:
    - kvmhost_storage_enabled | default(true)
    - kvmhost_storage_backup_enabled | default(false)

- name: Display completion summary
  ansible.builtin.debug:
    msg:
      - === KVM Host Storage Configuration Complete ===
      - "Total storage pools: {{ (kvmhost_storage_advanced_pools      | selectattr('enabled')      |      list | length) + (kvmhost_storage_lvm_volumes | selectattr('enabled') |
        list           |  length)    }}"
      - "LVM volumes: {{ kvmhost_storage_lvm_volumes      | selectattr('enabled')      |      list | map(attribute='name')           |  join(', ') if kvmhost_storage_lvm_enabled else 'None'    }}"
      - "Performance optimization: {{ 'Applied' if kvmhost_storage_performance_enabled else 'Skipped' }}"
  when: kvmhost_storage_debug_enabled | default(false)
