---
# =============================================================================
# STORAGE VALIDATION TASKS
# =============================================================================
# Validate storage prerequisites and configuration

- name: Check if LVM device exists
  ansible.builtin.stat:
    path: /dev/{{ kvmhost_storage_lvm_device }}
  register: lvm_device_check
  when:
    - kvmhost_storage_lvm_enabled | default(false)
    - kvmhost_storage_lvm_device | length > 0

- name: Validate LVM device availability
  ansible.builtin.fail:
    msg: LVM device /dev/{{ kvmhost_storage_lvm_device }} not found
  when:
    - kvmhost_storage_lvm_enabled | default(false)
    - kvmhost_storage_lvm_device | length > 0
    - not lvm_device_check.stat.exists

- name: Check if LVM device is already in use
  ansible.builtin.command: pvdisplay /dev/{{ kvmhost_storage_lvm_device }}
  register: pv_check
  changed_when: false
  failed_when: false
  when:
    - kvmhost_storage_lvm_enabled | default(false)
    - kvmhost_storage_lvm_device | length > 0
    - lvm_device_check.stat.exists

- name: Display LVM device status
  ansible.builtin.debug:
    msg: "LVM device /dev/{{ kvmhost_storage_lvm_device }} status: {{ 'In use' if pv_check.rc == 0 else 'Available' }}"
  when:
    - kvmhost_storage_lvm_enabled | default(false)
    - kvmhost_storage_lvm_device | length > 0
    - lvm_device_check.stat.exists
    - kvmhost_storage_debug_enabled | default(false)

- name: Check current disk space for storage directories
  ansible.builtin.command: df -h {{ item.path if item.path is defined else item.mount_dir }}
  register: storage_space_check
  changed_when: false
  failed_when: false
  loop: "{{ kvmhost_storage_advanced_pools + kvmhost_storage_lvm_volumes }}"
  when: item.enabled | default(true)

- name: Validate minimum free space requirements
  ansible.builtin.shell: |
    df --output=avail -BG /var/lib/libvirt | tail -1 | tr -d 'G'
  register: available_space_check
  changed_when: false

- name: Assert minimum storage space available
  ansible.builtin.assert:
    that:
      - available_space_check.stdout | int >= kvmhost_storage_minimum_free_space
    fail_msg: "Insufficient storage space. Available: {{ available_space_check.stdout }}GB, Required: {{ kvmhost_storage_minimum_free_space
      }}GB"
    success_msg: "Storage space validation passed. Available: {{ available_space_check.stdout }}GB"

- name: Check for required LVM packages
  ansible.builtin.ansible.builtin.package:
    name:
      - lvm2
      - xfsprogs
    state: present
  become: true
  when: kvmhost_storage_lvm_enabled | default(false)
