---
# Test playbook for modular roles - Cockpit and User Config
- name: Test kvmhost_cockpit and kvmhost_user_config roles syntax
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Disable actual execution, just test syntax
    kvmhost_cockpit_enabled: false
    kvmhost_user_config_enabled: false
  roles:
    - role: kvmhost_cockpit
    - role: kvmhost_user_config
