galaxy_info:
  role_name: kvmhost_libvirt
  author: Qubinode Community
  description: Configure libvirt services, storage pools, and virtualization settings for KVM hosts
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - all
  
  galaxy_tags:
    - libvirt
    - kvm
    - virtualization
    - storage
    - rhel
    - rocky
    - centos

dependencies:
  - role: kvmhost_base
    when: kvmhost_libvirt_require_base | default(true)
  - role: kvmhost_networking
    when: kvmhost_libvirt_require_networking | default(true)

collections:
  - community.libvirt
  - ansible.posix
