---
# =============================================================================
# LIBVIRT SERVICE CONFIGURATION
# =============================================================================
kvmhost_libvirt_enabled: true
kvmhost_libvirt_autostart: true
kvmhost_libvirt_require_base: true
kvmhost_libvirt_require_networking: true

# Libvirt services to manage
kvmhost_libvirt_services:
  - libvirtd
  - tuned

# Tuned profile for virtualization
kvmhost_libvirt_tuned_profile: "virtual-host"

# =============================================================================
# STORAGE POOL CONFIGURATION
# =============================================================================
kvmhost_libvirt_storage_enabled: true
kvmhost_libvirt_storage_pools:
  - name: default
    state: active
    autostart: true
    path: "/var/lib/libvirt/images"
    type: "dir"

# Legacy compatibility
kvm_host_libvirt_dir: "/var/lib/libvirt/images"
libvirt_images_dir: "/var/lib/libvirt/images" 
libvirt_pool_name: "default"
create_libvirt_storage: true
libvirt_host_storage_pools: "{{ kvmhost_libvirt_storage_pools }}"

# =============================================================================
# NETWORK CONFIGURATION
# =============================================================================
kvmhost_libvirt_networks_enabled: true
kvmhost_libvirt_networks:
  - name: "vmnetbr0"
    create: true
    mode: bridge
    bridge_name: "{{ kvmhost_bridge_device | default('vmbr0') }}"

# Legacy compatibility
kvmhost_bridge_device: "vmbr0"
qubinode_bridge_name: "qubibr0"
kvm_host_domain: "example.com"
libvirt_networks: "{{ kvmhost_libvirt_networks }}"
libvirt_host_networks: "{{ kvmhost_libvirt_networks }}"

# =============================================================================
# USER ACCESS CONFIGURATION
# =============================================================================
kvmhost_libvirt_user_access_enabled: true
kvmhost_libvirt_admin_group: "libvirt"
kvmhost_libvirt_admin_users: []

# Socket permissions
kvmhost_libvirt_unix_sock_group: "libvirt"
kvmhost_libvirt_unix_sock_rw_perms: "0770"
kvmhost_libvirt_unix_sock_admin_perms: "0700"

# Legacy compatibility  
enable_libvirt_admin_user: "{{ kvmhost_libvirt_user_access_enabled }}"
kvm_host_group: "{{ kvmhost_libvirt_admin_group }}"

# =============================================================================
# VALIDATION CONFIGURATION
# =============================================================================
kvmhost_libvirt_validation_enabled: true
kvmhost_libvirt_skip_vt_check: false

# Performance and resource settings
kvmhost_libvirt_memory_overcommit: false
kvmhost_libvirt_cpu_overcommit: false

# =============================================================================
# DNS AND DOMAIN CONFIGURATION
# =============================================================================
kvmhost_libvirt_dns_forwarder: "1.1.1.1"
kvmhost_libvirt_search_domains:
  - "{{ kvm_host_domain | default('example.com') }}"

# Legacy compatibility
primary_dns_server: "{{ kvmhost_libvirt_dns_forwarder }}"
dns_forwarder: "{{ kvmhost_libvirt_dns_forwarder }}"
domain: "{{ kvm_host_domain | default('example.com') }}"
search_domains: "{{ kvmhost_libvirt_search_domains }}"
