# =============================================================================
# KVMHOST USER CONFIG ROLE - VARIABLES
# =============================================================================
# Internal variables for the role
