# =============================================================================
# LIBVIRT NETWORK CONFIGURATION
# =============================================================================
# Configure libvirt virtual networks

- name: Display networks to configure
  ansible.builtin.debug:
    msg: "Configuring libvirt networks: {{ kvmhost_libvirt_networks | map(attribute='name') | join(', ') }}"
  when: kvmhost_libvirt_debug_enabled | default(false)

- name: Include network creation tasks
  ansible.builtin.include_tasks: create_network.yml
  loop: "{{ kvmhost_libvirt_networks }}"
  loop_control:
    loop_var: network_item
    index_var: network_idx
  when: network_item.create | default(true)

- name: Verify libvirt networks are active
  ansible.builtin.command: virsh net-info {{ item.name }}
  register: network_info_check
  changed_when: false
  failed_when: false
  loop: "{{ kvmhost_libvirt_networks }}"
  become: true

- name: Display network status
  ansible.builtin.debug:
    msg:
      - "Network: {{ item.item.name }}"
      - "Status: {{ 'Active' if 'State:     active' in item.stdout else 'Inactive' }}"
      - "Mode: {{ item.item.mode | default('bridge') }}"
  loop: "{{ network_info_check.results }}"
  when:
    - kvmhost_libvirt_debug_enabled | default(false)
    - item.rc == 0
