# Base Service Management

- name: "Enable base services"
  ansible.builtin.ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop: "{{ base_services_enabled }}"
  become: true
  register: service_enable
  failed_when: false

- name: "Start base services"
  ansible.builtin.ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  loop: "{{ base_services_started }}"
  become: true
  register: service_start
  failed_when: false

- name: "Verify service status"
  ansible.builtin.ansible.builtin.systemd:
    name: "{{ item }}"
  register: service_status
  loop: "{{ base_services_enabled }}"
  become: true

- name: "Display service status"
  ansible.builtin.debug:
    msg: |
      Service {{ item.item }} status:
      - Active: {{ item.status.ActiveState }}
      - Enabled: {{ item.status.UnitFileState }}
  loop: "{{ service_status.results }}"
  when: service_status is defined
