# System Preparation Tasks

- name: Configure kernel modules for KVM
  ansible.builtin.community.general.community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - kvm
    - kvm_intel
    - kvm_amd
  become: true
  failed_when: false
  register: kvm_modules

- name: Check KVM hardware support
  ansible.builtin.command: lscpu | grep -E '(vmx|svm)'
  register: kvm_support
  changed_when: false
  failed_when: false

- name: Display KVM support status
  ansible.builtin.debug:
    msg: |
      KVM Hardware Support:
      {{ 'Virtualization extensions detected' if kvm_support.rc == 0 else 'No virtualization extensions found' }}
      {{ kvm_support.stdout if kvm_support.stdout else 'Check BIOS settings for virtualization support' }}

- name: Set kernel parameters for KVM
  ansible.posix.ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: net.bridge.bridge-nf-call-iptables, value: "1" }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: "1" }
    - { name: net.ipv4.ip_forward, value: "1" }
  become: true
  failed_when: false

- name: Create system preparation completion marker
  ansible.builtin.ansible.builtin.file:
    path: /var/lib/kvmhost_base_prepared
    state: touch
    mode: "0644"
  become: true
