- name: Validate packages are installed
  ansible.builtin.dnf:
    list: "{{ item }}"
  with_items: "{{ libvirt_pkgs }}"
  register: edge_hosts_validate_installed_pkg
  become: true
  ignore_errors: true
  failed_when: not edge_hosts_validate_installed_pkg
  tags:
    - validate
    - validate_pkgs
