- name: Get list of libvirt networks
  community.libvirt.virt_net:
    command: list_nets
  register: libvirt_nets

- name: Ensure libvirt networks are setup
  vars:
    net_name: "{{ item.name }}"
    net_mode: "{{ item.mode }}"
    net_create: "{{ item.create }}"
  when: net_name not in libvirt_nets.list_nets and net_create|bool
  with_items: "{{ libvirt_host_networks }}"
  block:
    - name: Ensure libvirt nat network is defined
      community.libvirt.virt_net:
        name: "{{ net_name }}"
        command: define
        xml: '{{ lookup("template", "nat_network.xml.j2") }}'
      when: net_mode == 'nat'

- name: Ensure libvirt networks are active
  community.libvirt.virt_net:
    name: "{{ item.name }}"
    state: active
  with_items: "{{ libvirt_host_networks }}"

- name: Ensure libvirt networks start on boot
  community.libvirt.virt_net:
    name: "{{ item.name }}"
    autostart: true
  with_items: "{{ libvirt_host_networks }}"
