- name: Ensure libvirt pool is defined
  community.libvirt.virt_pool:
    command: define
    name: "{{ item.name }}"
    xml: '{{ (lookup("template", "libvirt_pool.xml.j2")) }}'
  with_items: "{{ libvirt_host_storage_pools }}"
  become: true

- name: Ensure libvirt storage pool is active
  community.libvirt.virt_pool:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
  with_items: "{{ libvirt_host_storage_pools }}"

- name: Ensure storage pool is started at boot
  community.libvirt.virt_pool:
    autostart: "{{ item.autostart }}"
    name: "{{ item.name }}"
  with_items: "{{ libvirt_host_storage_pools }}"
