- name: Verify that Virtualization Technology (VT) is enabled
  ansible.builtin.command: grep -c -E 'svm|vmx' /proc/cpuinfo
  changed_when: false
  failed_when: false
  register: result

- name: Set a fact about whether Virtualization Technology (VT) is enabled
  ansible.builtin.set_fact:
    libvirt_host_vt_enabled: "{{ result.rc == 0 }}"

- name: Notify if Virtualization Technology (VT) is disabled
  ansible.builtin.debug:
    msg: >
      Virtualization Technology (VT) is currently disabled. Please enable VT
      before running this role again.
  when: not libvirt_host_vt_enabled

- name: Fail if Virtualization Technology (VT) is disabled
  ansible.builtin.fail:
    msg: >
      Virtualization Technology (VT) is currently disabled. Please enable VT
      before running this role again.
  when: not libvirt_host_vt_enabled
