- name: Reload libvirtd service
  ansible.builtin.service:
    name: libvirtd
    state: reloaded
  become: true

- name: Restart libvirtd service
  ansible.builtin.service:
    name: libvirtd
    state: restarted
  become: true

- name: Restart tuned service
  ansible.builtin.service:
    name: tuned
    state: restarted
  become: true
