- name: Create Volume Group
  community.general.lvg:
    vg: "{{ vg_name }}"
    force: true
    pvs: /dev/{{ host_device }}
  when: create_vg|bool
  become: true

- name: Create custom logical volumes
  community.general.lvol:
    lv: lv_{{ item.name }}
    vg: "{{ vg_name }}"
    state: present
    size: "{{ item.size }}"
  with_items: "{{ logical_volumes }}"
  when: create_vg|bool
  become: true

- name: Ensure filesystems are created
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: /dev/mapper/{{ vg_name }}-lv_{{ item.name }}
    opts: -L {{ item.name }}
  with_items: "{{ logical_volumes }}"
  when: create_vg|bool
  become: true

- name: Ensure mount points are created
  ansible.builtin.ansible.builtin.file:
    path: "{{ item.mount_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: wheel
  with_items: "{{ logical_volumes }}"
  when: create_vg|bool
  become: true

- name: Config mount points in fstab
  ansible.posix.ansible.posix.mount:
    name: "{{ item.mount_dir }}"
    src: /dev/mapper/{{ vg_name }}-lv_{{ item.name }}
    fstype: "{{ item.fstype }}"
    dump: 0
    passno: 0
    opts: defaults
    state: mounted
  with_items: "{{ logical_volumes }}"
  become: true

- name: Show device info
  ansible.builtin.debug:
    msg: "{{ item.name }}"
    verbosity: 1
  with_items: "{{ logical_volumes }}"
  when: create_vg|bool
  become: true
