---
- name: "Molecule Converge - Modular Role Testing"
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    # Test mode configuration
    testing_mode: true
    cicd_test: true
    idempotency_test: "{{ lookup('env', 'IDEMPOTENCY_TEST') | default(false) | bool }}"
    
    # Modular role configuration
    enable_base_config: true
    enable_networking: true
    enable_legacy_kvmhost: false
    
    # Network configuration for testing
    qubinode_bridge_name: "testbr0"
    network_validation_enabled: true
    auto_detect_interface: true
    backup_existing_config: false  # Skip backup in test environment
    
    # Basic test variables
    admin_user: molecule
    domain: test.local
    dns_forwarder: "1.1.1.1"

  pre_tasks:
    - name: "Update package cache (OS-aware)"
      ansible.builtin.package:
        update_cache: true
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: "Install test dependencies"
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - iproute
          - NetworkManager
        state: present

    - name: "Ensure NetworkManager is started"
      ansible.builtin.systemd:
        name: NetworkManager
        state: started
        enabled: true

    - name: "Create test user"
      ansible.builtin.user:
        name: "{{ admin_user }}"
        state: present
        create_home: true
        shell: /bin/bash
        groups: wheel
        append: true

  roles:
    # Test modular base configuration
    - role: kvmhost_base
      when: enable_base_config | default(true)
      tags:
        - base
        - modular_test

    # Test modular networking (with constraints for containers)
    - role: kvmhost_networking  
      when: 
        - enable_networking | default(true)
        - not (ansible_virtualization_type | default('') == 'docker')
      tags:
        - networking
        - modular_test

  post_tasks:
    - name: "Display test completion status"
      ansible.builtin.debug:
        msg: |
          Modular Role Testing Complete:
          - Test Mode: {{ testing_mode }}
          - CICD Test: {{ cicd_test }}
          - Idempotency Test: {{ idempotency_test }}
          - Base Config: {{ enable_base_config }}
          - Networking: {{ enable_networking and not (ansible_virtualization_type | default('') == 'docker') }}
          - Host: {{ inventory_hostname }}
          - OS: {{ ansible_distribution }} {{ ansible_distribution_version }}

    - name: "Verify base role completion marker"
      ansible.builtin.stat:
        path: "/var/lib/kvmhost_base_prepared"
      register: base_marker
      when: enable_base_config

    - name: "Assert base configuration completed"
      ansible.builtin.assert:
        that:
          - base_marker.stat.exists
        fail_msg: "Base configuration marker not found"
        success_msg: "Base configuration completed successfully"
      when: enable_base_config

    - name: "Create molecule test completion marker"
      ansible.builtin.file:
        path: "/var/lib/molecule_modular_test_complete"
        state: touch
        mode: '0644'
