---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  # Podman driver for local development
  name: podman
  options:
    podman_binary: /usr/bin/podman
    podman_extra_args: --log-level=info
    ansible_connection_options:
      ansible_podman_executable: /usr/bin/podman

platforms:
  # RHEL 9 compatible - Rocky Linux 9 (Init Container)
  - name: rocky-9
    image: docker.io/rockylinux/rockylinux:9-ubi-init
    dockerfile: Dockerfile.rhel
    pre_build_image: false
    systemd: always
    command: "/usr/sbin/init"
    # Security-enhanced configuration per ADR-0012 (no privileged containers)
    capabilities:
      - SYS_ADMIN
    groups:
      - rhel9_compatible
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible_user: root
    ansible_connection: podman

  # AlmaLinux 9 Init Container (ADR-0012 compliant)
  - name: alma-9
    image: docker.io/almalinux/9-init:9.6-20250712
    dockerfile: Dockerfile.rhel
    pre_build_image: false
    systemd: always
    command: "/usr/sbin/init"
    # Security-enhanced configuration per ADR-0012 (no privileged containers)
    capabilities:
      - SYS_ADMIN
    groups:
      - rhel9_compatible
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible_user: root
    ansible_connection: podman

  # RHEL 9 - Official Red Hat UBI 9 init image (Recommended)
  - name: rhel-9
    image: registry.redhat.io/ubi9-init:9.6-1751962289
    dockerfile: Dockerfile.rhel
    pre_build_image: false
    systemd: always
    command: "/usr/sbin/init"
    # Security-enhanced configuration per ADR-0012 (no privileged containers)
    capabilities:
      - SYS_ADMIN
    groups:
      - rhel9_compatible
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible_user: root
    ansible_connection: podman

  # RHEL 10 - Official Red Hat UBI 10 init image (Latest)
  - name: rhel-10
    image: registry.redhat.io/ubi10-init:10.0-1751895590
    dockerfile: Dockerfile.rhel
    pre_build_image: false
    systemd: always
    command: "/usr/sbin/init"
    # Security-enhanced configuration per ADR-0012 (no privileged containers)
    capabilities:
      - SYS_ADMIN
    groups:
      - rhel10_compatible
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ansible_user: root
    ansible_connection: podman

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: "1"
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      host_key_checking: false
      deprecation_warnings: false
      roles_path: "../../roles"
    ssh_connection:
      pipelining: true
  playbooks:
    converge: converge.yml
    verify: verify.yml

lint: |
  set -e
  yamllint .
  ansible-lint roles/kvmhost_setup/ --exclude .github/

verifier:
  name: testinfra
  options:
    verbose: true

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
