---
# Molecule Prepare Playbook
# Purpose: Pre-configure testing environment with EPEL GPG keys
# Related: docs/research/epel-gpg-verification-in-container-testing.md
# ADR References: ADR-0012 (Container Security), ADR-0011 (Local Testing)

- name: Prepare testing environment
  hosts: all:!localhost
  become: true
  gather_facts: true
  vars:
    # EPEL GPG keys for different RHEL versions
    epel_gpg_keys:
      - url: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8"
        key_id: "8"
        applicable_versions: ["8"]
      - url: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"
        key_id: "9"
        applicable_versions: ["9", "10"]

  tasks:
    - name: Wait for container to be ready
      wait_for_connection:
        timeout: 60
        delay: 5
      when: ansible_connection == 'podman'

    - name: Display testing environment information
      debug:
        msg: |
          Preparing testing environment for: {{ inventory_hostname }}
          OS Family: {{ ansible_os_family }}
          Distribution: {{ ansible_distribution }}
          Version: {{ ansible_distribution_major_version }}
          Connection: {{ ansible_connection | default('ssh') }}

    - name: Ensure basic packages are available (skip curl due to container conflicts)
      package:
        name:
          - gnupg2
          - rpm
        state: present
      ignore_errors: true

    # Research Finding: Container environments require manual GPG key import
    # Evidence: GitHub Issue #20711, Ansible 2.9.13+ breaking changes
    - name: Pre-import EPEL GPG keys for container testing
      block:
        - name: Import EPEL GPG key for RHEL/Rocky/AlmaLinux 8
          rpm_key:
            key: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8"
            state: present
          when: ansible_distribution_major_version == "8"
          ignore_errors: true

        - name: Import EPEL GPG key for RHEL/Rocky/AlmaLinux 9+
          rpm_key:
            key: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"
            state: present
          when: ansible_distribution_major_version in ["9", "10"]
          ignore_errors: true

        # Fallback method based on research evidence
        - name: Fallback GPG key import using rpm command (RHEL 8)
          shell: |
            curl -sSL https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8 | rpm --import -
          when: 
            - ansible_distribution_major_version == "8"
          ignore_errors: true
          changed_when: false

        - name: Fallback GPG key import using rpm command (RHEL 9+)
          shell: |
            curl -sSL https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9 | rpm --import -
          when: 
            - ansible_distribution_major_version in ["9", "10"]
          ignore_errors: true
          changed_when: false

      rescue:
        - name: Log GPG import failure
          debug:
            msg: |
              GPG key import failed - this is expected in some container environments.
              Tests will use disable_gpg_check workaround per research findings.

    # Workaround for container testing per research evidence
    - name: Configure yum/dnf to handle GPG verification gracefully
      ini_file:
        path: /etc/dnf/dnf.conf
        section: main
        option: gpgcheck
        value: "1"
        backup: false
      ignore_errors: true

    # Additional workaround for EPEL GPG signature issues in containers
    # ADR-0018: Disable both gpgcheck and repo_gpgcheck for EPEL repos
    - name: Disable GPG verification for EPEL repositories in containers
      ini_file:
        path: "{{ item.path }}"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "0"
        backup: false
      loop:
        # gpgcheck controls package signature verification
        - { path: "/etc/yum.repos.d/epel.repo", section: "epel", option: "gpgcheck" }
        - { path: "/etc/yum.repos.d/epel-next.repo", section: "epel-next", option: "gpgcheck" }
        # repo_gpgcheck controls repository metadata (repomd.xml) signature verification
        # This is the setting that causes "GPG signature is not available" errors
        - { path: "/etc/yum.repos.d/epel.repo", section: "epel", option: "repo_gpgcheck" }
        - { path: "/etc/yum.repos.d/epel-next.repo", section: "epel-next", option: "repo_gpgcheck" }
      ignore_errors: true
      when: ansible_virtualization_type == "container"

    # Handle UBI repository GPG issues in RHEL containers (ADR-0018)
    - name: Disable repo_gpgcheck for UBI repositories in RHEL containers
      shell: |
        for repo_file in /etc/yum.repos.d/ubi*.repo; do
          if [ -f "$repo_file" ]; then
            # Add repo_gpgcheck=0 if not present, or change 1 to 0
            if grep -q "repo_gpgcheck" "$repo_file"; then
              sed -i 's/repo_gpgcheck=1/repo_gpgcheck=0/g' "$repo_file"
            else
              # Add repo_gpgcheck=0 after each section header
              sed -i 's/^\(\[.*\]\)$/\1\nrepo_gpgcheck=0/' "$repo_file"
            fi
            echo "Fixed $repo_file"
          fi
        done
      args:
        executable: /bin/bash
      ignore_errors: true
      changed_when: false
      when:
        - ansible_virtualization_type == "container"
        - ansible_distribution == "RedHat"

    # Clean DNF cache after modifying repo configs to ensure changes take effect
    - name: Clean DNF cache after repo modifications
      shell: dnf clean all 2>/dev/null || yum clean all 2>/dev/null || true
      args:
        executable: /bin/bash
      changed_when: false
      ignore_errors: true
      when: ansible_virtualization_type == "container"

    - name: Verify GPG key import status
      shell: rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
      register: gpg_keys_status
      changed_when: false
      ignore_errors: true

    - name: Display GPG key status
      debug:
        var: gpg_keys_status.stdout_lines
      when: gpg_keys_status.stdout_lines is defined

    - name: Ensure systemd is functional (for systemd-enabled containers)
      service:
        name: systemd-logind
        state: started
      ignore_errors: true
      when: 
        - ansible_service_mgr == "systemd"
        - ansible_virtualization_type == "container"

    # Install required Ansible collections and roles into containers
    - name: Install Ansible collections and roles for testing
      block:
        - name: Install pip packages for Ansible collection management
          pip:
            name:
              - ansible-core
              - requests
            state: present
          register: pip_install_result
          failed_when: false  # Don't fail immediately, but track result

        - name: Ensure ansible-galaxy is available in PATH
          ansible.builtin.shell: |
            if command -v ansible-galaxy >/dev/null 2>&1; then
              echo "SUCCESS: ansible-galaxy found in PATH"
              exit 0
            elif [ -f /usr/local/bin/ansible-galaxy ]; then
              ln -sf /usr/local/bin/ansible-galaxy /usr/bin/ansible-galaxy
              echo "SUCCESS: ansible-galaxy linked from /usr/local/bin"
              exit 0
            elif [ -f ~/.local/bin/ansible-galaxy ]; then
              export PATH="$HOME/.local/bin:$PATH"
              echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
              echo "SUCCESS: ansible-galaxy found in ~/.local/bin, PATH updated"
              exit 0
            else
              echo "WARNING: ansible-galaxy not found in common locations"
              exit 1
            fi
          register: galaxy_path_result
          failed_when: false
          changed_when: false

        - name: Install required Ansible collections
          ansible.builtin.shell: |
            if command -v ansible-galaxy >/dev/null 2>&1; then
              echo "Installing collection: {{ item }}"
              ansible-galaxy collection install {{ item }} --force
              echo "SUCCESS: {{ item }} installed"
            else
              echo "ERROR: ansible-galaxy not available for {{ item }}"
              exit 1
            fi
          loop:
            - ansible.posix
            - community.general
            - community.libvirt
            - fedora.linux_system_roles
            - ansible.netcommon
          register: collection_install_results
          failed_when: false
          changed_when: false

        - name: Install linux-system-roles.network role
          ansible.builtin.shell: |
            if command -v ansible-galaxy >/dev/null 2>&1; then
              echo "Installing role: linux-system-roles.network"
              ansible-galaxy role install linux-system-roles.network --force
              echo "SUCCESS: linux-system-roles.network installed"
            else
              echo "ERROR: ansible-galaxy not available for role installation"
              exit 1
            fi
          register: role_install_result
          failed_when: false
          changed_when: false

        - name: Check critical collections availability
          ansible.builtin.shell: |
            echo "Verifying required Ansible collections for testing..."
            echo ""

            # Note: Collection verification in containers can be unreliable due to Python path differences
            # between pip-installed ansible-core and the shell environment. The actual converge phase
            # will fail if collections are truly missing, providing the real validation.

            # Try to find collections via ansible-galaxy (most reliable method)
            if command -v ansible-galaxy >/dev/null 2>&1; then
              echo "📋 Installed collections (via ansible-galaxy):"
              ansible-galaxy collection list 2>/dev/null | head -20 || echo "  Unable to list collections"
            fi

            echo ""
            echo "📁 Checking collection paths:"
            for path in /root/.ansible/collections /usr/share/ansible/collections /usr/local/lib/python*/site-packages/ansible_collections; do
              if [ -d "$path" ]; then
                echo "  ✓ Found: $path"
                ls "$path" 2>/dev/null | head -5 || true
              fi
            done

            echo ""
            echo "✅ Collection verification complete - converge phase will validate actual availability"
            exit 0
          register: collection_verification
          failed_when: false
          changed_when: false

        - name: Display installation summary
          debug:
            msg: |
              📋 Installation Summary:
              • Pip packages: {{ 'SUCCESS' if not pip_install_result.failed else 'FAILED' }}
              • ansible-galaxy PATH: {{ 'SUCCESS' if galaxy_path_result.rc == 0 else 'WARNING' }}
              • Collections: Installed (verification via converge phase)
              • Ready for testing - converge will validate actual collection availability

      rescue:
        - name: Collection setup warning
          debug:
            msg: |
              ⚠️  Collection setup encountered issues but continuing...

              📊 Diagnostic Information:
              • Pip packages (ansible-core): {{ 'FAILED' if pip_install_result.failed | default(false) else 'OK' }}
              • ansible-galaxy command: {{ 'FAILED' if galaxy_path_result.rc | default(0) != 0 else 'OK' }}

              📝 Note: Collections are installed in the container image via Dockerfile.
              The converge phase will validate actual collection availability.
              If collections are truly missing, the converge phase will fail with clear errors.

    - name: Create testing marker file
      file:
        path: /tmp/molecule-prepare-complete
        state: touch
        mode: '0644'
