- name: Include package management tasks
  ansible.builtin.include_tasks: packages.yml

- name: Include libvirt configuration tasks
  ansible.builtin.include_tasks: libvirt.yml
  when: lib_virt_setup | bool

- name: Include network configuration tasks
  ansible.builtin.include_tasks: networking.yml
  when: libvirt_host_networks is defined and libvirt_host_networks | length > 0

- name: Include storage configuration tasks
  ansible.builtin.include_tasks: storage.yml
  when: create_libvirt_storage | bool
