---
# =============================================================================
# KVMHOST USER CONFIG ROLE - HANDLERS
# =============================================================================
# Handlers for user configuration changes

- name: Reload bash profile
  ansible.builtin.shell:
    cmd: source ~/.bashrc
  become: true
  become_user: "{{ kvmhost_user_config_target_user }}"
  listen: reload bash profile

- name: Restart ssh service
  ansible.builtin.ansible.builtin.systemd:
    name: sshd
    state: restarted
  listen: restart ssh service

- name: Reload user shell
  ansible.builtin.shell:
    cmd: exec $SHELL
  become: true
  become_user: "{{ kvmhost_user_config_target_user }}"
  listen: reload user shell
