# =============================================================================
# KVMHOST COCKPIT ROLE - PACKAGE INSTALLATION
# =============================================================================
# Installs Cockpit and related packages following ADR-0001 package management

- name: Install Cockpit base packages
  ansible.builtin.dnf:
    name: "{{ kvmhost_cockpit_packages }}"
    state: present
    update_cache: true
  register: cockpit_install
  retries: 3
  delay: 5
  until: cockpit_install is succeeded

- name: Install additional Cockpit modules
  ansible.builtin.dnf:
    name: "{{ kvmhost_cockpit_additional_packages }}"
    state: present
  register: cockpit_modules_install
  retries: 3
  delay: 5
  until: cockpit_modules_install is succeeded
  when: kvmhost_cockpit_additional_packages | length > 0

- name: Verify Cockpit installation
  ansible.builtin.command:
    cmd: rpm -q cockpit
  register: cockpit_verify
  changed_when: false
  failed_when: cockpit_verify.rc != 0

- name: Display installed Cockpit packages
  ansible.builtin.debug:
    msg:
      - "Cockpit packages installed successfully"
      - "Base packages: {{ kvmhost_cockpit_packages | join(', ') }}"
      - "Additional packages: {{ kvmhost_cockpit_additional_packages | join(', ') if kvmhost_cockpit_additional_packages |
        length > 0 else 'None' }}"
