---
# GitHub Actions Rocky Linux Runner Inventory Variables
# Configuration for the Rocky Linux shared runner instance (NOT RHEL)
# This inventory is specifically for Rocky Linux systems running GitHub Actions
# Based on inventories/test/group_vars/all.yml with Rocky Linux specific modifications

# System Configuration - Rocky Linux Specific
project_dir: /opt/qubinode-installer
admin_user: runner
domain: github-runner.example.com
rhel_version: "9.0"  # Keep for compatibility
rocky_version: "9.0"
actual_os: "rocky"  # Explicitly mark this as Rocky Linux

# GitHub Actions Runner Environment Settings - Rocky Linux
run_on_rhpds: false
run_kni_lab_on_rhpds: false
one_redhat: false
ci_environment: true
github_actions_runner: true
runner_os: rocky_linux
target_os_family: "RedHat"  # Rocky is RedHat family
target_distribution: "Rocky"  # But specifically Rocky Linux
use_rocky_repos: true  # Use Rocky Linux repositories, not RHEL

# EPEL Repository Configuration
enable_epel: true  # Enable EPEL repository
epel_gpg_check: false  # Disable GPG verification for EPEL (default for CI)
epel_gpg_import_keys: true  # Import GPG keys (for optional future use)

# Application Dependencies (minimal for CI)
ansible_automation_platform: false
enable_ceph_deployment: false

# Networking Configuration (Rocky Linux Runner optimized)
# Using loopback address for local runner operations
kvm_host_ip: 127.0.0.1
kvm_host_netmask: 255.0.0.0
kvm_host_gateway: 127.0.0.1
kvm_host_gw: "{{ kvm_host_gateway }}"
kvm_host_dns: 127.0.0.1
kvm_host_bridge: virbr0
kvm_host_interface: lo
kvm_host_mac: "00:00:00:00:00:00"
kvm_host_macaddr: "00:00:00:00:00:00"
kvm_host_mask_prefix: 8
qubinode_ptr: localhost.localdomain
dns_forwarder: 127.0.0.1
convert_dhcp_to_static: false
kvm_host_bootproto: static
kvm_bridge_type: bridge
qubinet: github-runner-net

# Subscription Management (disabled for CI)
rhsm_reg_method: ""
rhsm_setup_insights_client: false

# LVM Configuration (Rocky Linux Runner optimized)
logical_volumes:
  - name: runner_images
    size: +10G
    mount_dir: /var/lib/libvirt/images
    fstype: xfs

# User Configuration
users:
  - "{{ admin_user }}"
  - runner

# Required Packages (Rocky Linux Runner optimized)
# These packages are available in Rocky Linux repositories
required_rpm_packages:
  - virt-install
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - libguestfs-tools
  - libvirt-client
  - qemu-kvm
  - libvirt-daemon
  - openssh-server
  - wget
  - git
  - net-tools
  - bind-utils
  - bash-completion
  - vim
  - python3-dns
  - python3-lxml
  - curl
  - podman
  - buildah
  - skopeo
  - epel-release  # Rocky Linux has EPEL available

# Libvirt Configuration
kvm_host_libvirt_dir: /var/lib/libvirt/images
kvm_vm_pool_dir: "{{ kvm_host_libvirt_dir }}"
host_device: "{{ kvm_host_libvirt_extra_disk | default('vda') }}"
vg_name: vg_runner
vm_libvirt_net_check: false
kvm_host_libvirt_extra_disk: vda

# GitHub Actions Runner specific settings
setup_nfs: false
remove_nfs: false
libvirt_pool_name: default
qubinode_installer_host_completed: false

# Performance optimizations for GitHub Actions Runner
enable_cockpit: false
configure_shell: false
lib_virt_setup: true
github_actions_environment: true
