---
# GitHub Actions CI/CD Inventory Variables
# Optimized for containerized testing environments
# Based on inventories/test/group_vars/all.yml with CI-specific modifications

# System Configuration
project_dir: /opt/qubinode-installer
admin_user: github-runner
domain: ci.example.com
rhel_version: "9.0"

# CI/CD Environment Settings
run_on_rhpds: false
run_kni_lab_on_rhpds: false
one_redhat: false
ci_environment: true

# Application Dependencies (minimal for CI)
ansible_automation_platform: false
enable_ceph_deployment: false

# Networking Configuration (CI-optimized)
kvm_host_ip: 10.0.2.15
kvm_host_netmask: 255.255.255.0
kvm_host_gateway: 10.0.2.2
kvm_host_gw: "{{ kvm_host_gateway }}"
kvm_host_dns: 1.1.1.1
kvm_host_bridge: virbr0
kvm_host_interface: eth0
kvm_host_mac: "02:00:00:00:00:10"
kvm_host_macaddr: "02:00:00:00:00:11"
kvm_host_mask_prefix: 24
qubinode_ptr: ci.in-addr.arpa
dns_forwarder: 1.1.1.1
convert_dhcp_to_static: false
kvm_host_bootproto: dhcp
kvm_bridge_type: bridge
qubinet: ci-qubinode-net

# Subscription Management (disabled for CI)
rhsm_reg_method: ""
rhsm_setup_insights_client: false

# LVM Configuration (minimal for CI)
logical_volumes:
  - name: ci_images
    size: +5G
    mount_dir: /var/lib/libvirt/images
    fstype: xfs

# User Configuration
users:
  - "{{ admin_user }}"

# Required Packages (essential only for CI)
required_rpm_packages:
  - virt-install
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - libguestfs-tools
  - libvirt-client
  - qemu-kvm
  - libvirt-daemon
  - openssh-server
  - wget
  - git
  - net-tools
  - bind-utils
  - bash-completion
  - vim
  - python3-dns
  - python3-lxml
  - curl

# Libvirt Configuration
kvm_host_libvirt_dir: /var/lib/libvirt/images
kvm_vm_pool_dir: "{{ kvm_host_libvirt_dir }}"
host_device: "{{ kvm_host_libvirt_extra_disk | default('vda') }}"
vg_name: vg_ci
vm_libvirt_net_check: false
kvm_host_libvirt_extra_disk: vda

# CI-specific settings
setup_nfs: false
remove_nfs: false
libvirt_pool_name: default
qubinode_installer_host_completed: false

# Performance optimizations for CI
enable_cockpit: false
configure_shell: false
lib_virt_setup: true
