---
# Idempotency testing scenario for Molecule
# Tests all roles for idempotency compliance using only init containers
# Updated per ADR-0012: Uses systemd-enabled base images only
# Available images documented in: molecule/AVAILABLE_INIT_IMAGES.md

dependency:
  name: galaxy
  options:
    requirements-file: ../../roles/kvmhost_setup/collection/requirements.yml

driver:
  name: podman
  options:
    podman_extra_args: --systemd=true --log-level=info
  
platforms:
  - name: idempotency-rocky9
    image: docker.io/rockylinux/rockylinux:9-ubi-init
    pre_build_image: true
    override_command: false
    systemd: always
    command: "/usr/sbin/init"
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    
  - name: idempotency-alma9
    image: docker.io/almalinux/9-init:9.6-20250712
    pre_build_image: true
    override_command: false
    systemd: always
    command: "/usr/sbin/init"
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    
  - name: idempotency-rhel9
    image: registry.redhat.io/ubi9-init:9.6-1751962289
    pre_build_image: true
    override_command: false
    systemd: always
    command: "/usr/sbin/init"
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    
  - name: idempotency-rhel10
    image: registry.redhat.io/ubi10-init:10.0-1751895590
    pre_build_image: true
    override_command: false
    systemd: always
    command: "/usr/sbin/init"
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      idempotency-rocky9:
        ansible_python_interpreter: /usr/bin/python3
        testing_mode: true
        idempotency_test: true
      idempotency-alma9:
        ansible_python_interpreter: /usr/bin/python3
        testing_mode: true
        idempotency_test: true
      idempotency-rhel9:
        ansible_python_interpreter: /usr/bin/python3
        testing_mode: true
        idempotency_test: true
      idempotency-rhel10:
        ansible_python_interpreter: /usr/bin/python3
        testing_mode: true
        idempotency_test: true
  ansible_args:
    - --timeout=30
    - -v
  config_options:
    defaults:
      callbacks_enabled: timer,profile_tasks
      host_key_checking: false
      retry_files_enabled: false
    ssh_connection:
      pipelining: true

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
