# =============================================================================
# CONFIGURATION DRIFT DETECTION
# =============================================================================
# Detects configuration drift from expected values and ADR compliance

- name: Initialize drift detection
  ansible.builtin.set_fact:
    configuration_drifts: []
    drift_detection_enabled: "{{ enable_drift_detection | default(false) }}"

- name: Check for EPEL installation method drift (ADR-0001)
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [epel_drift_msg] }}"
  vars:
    epel_drift_msg: >-
      Configuration drift detected: EPEL installation method is '{{ epel_installation_method }}'
      but ADR-0001 requires 'dnf_module'
  when:
    - drift_detection_enabled
    - enable_epel | default(false)
    - epel_installation_method is defined
    - epel_installation_method != 'dnf_module'

- name: Check for bridge device naming drift
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [bridge_naming_drift_msg] }}"
  vars:
    bridge_naming_drift_msg: >-
      Configuration drift detected: Bridge device '{{ kvmhost_bridge_device }}'
      doesn't follow recommended naming pattern (virbr*)
  when:
    - drift_detection_enabled
    - kvmhost_bridge_device is defined
    - not (kvmhost_bridge_device | regex_search('^virbr[0-9]+$'))

- name: Check for libvirt directory drift
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [libvirt_dir_drift_msg] }}"
  vars:
    libvirt_dir_drift_msg: >-
      Configuration drift detected: Libvirt directory '{{ kvm_host_libvirt_dir }}'
      is not the standard '/var/lib/libvirt'
  when:
    - drift_detection_enabled
    - kvm_host_libvirt_dir is defined
    - kvm_host_libvirt_dir != '/var/lib/libvirt'

- name: Check for cockpit port drift
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [cockpit_port_drift_msg] }}"
  vars:
    cockpit_port_drift_msg: >-
      Configuration drift detected: Cockpit port '{{ kvmhost_cockpit_port }}'
      is not the default 9090
  when:
    - drift_detection_enabled
    - enable_cockpit | default(false)
    - kvmhost_cockpit_port is defined
    - kvmhost_cockpit_port | int != 9090

- name: Check for SSH port drift
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [ssh_port_drift_msg] }}"
  vars:
    ssh_port_drift_msg: >-
      Configuration drift detected: SSH port '{{ ssh_configuration.ssh_port }}'
      is not the default 22
  when:
    - drift_detection_enabled
    - ssh_configuration is defined
    - ssh_configuration.ssh_port is defined
    - ssh_configuration.ssh_port | int != 22

- name: Check for admin user naming drift
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [admin_user_drift_msg] }}"
  vars:
    admin_user_drift_msg: >-
      Configuration drift detected: Admin user '{{ admin_user }}'
      doesn't follow recommended naming (admin/qubinode)
  when:
    - drift_detection_enabled
    - admin_user is defined
    - admin_user not in ['admin', 'qubinode']

- name: Check for storage pool type drift
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [storage_type_drift_msg] }}"
  vars:
    storage_type_drift_msg: >-
      Configuration drift detected: Storage pool '{{ item.name }}'
      uses type '{{ item.type }}' instead of recommended 'dir'
  when:
    - drift_detection_enabled
    - libvirt_host_storage_pools is defined
    - item.type != 'dir'
  loop: "{{ libvirt_host_storage_pools }}"

- name: Check environment template consistency
  ansible.builtin.include_tasks: validate_environment_template_consistency.yml
  when:
    - drift_detection_enabled
    - inventory_environment is defined

- name: Report configuration drifts
  ansible.builtin.debug:
    msg: |
      Configuration drift detection results:
      {% if configuration_drifts | length == 0 %}
      No configuration drifts detected - all settings follow ADR recommendations.
      {% else %}
      {{ configuration_drifts | length }} configuration drift(s) detected:
      {% for drift in configuration_drifts %}
      - {{ drift }}
      {% endfor %}
      {% endif %}
  when: drift_detection_enabled

- name: Add drift detection to warnings
  ansible.builtin.set_fact:
    validation_warnings: "{{ validation_warnings + configuration_drifts }}"
  when:
    - drift_detection_enabled
    - configuration_drifts | length > 0
