# =============================================================================
# ENVIRONMENT TEMPLATE CONSISTENCY VALIDATION
# =============================================================================
# Validates consistency with environment-specific templates

- name: Check if current environment matches template expectations
  ansible.builtin.set_fact:
    expected_template_path: "{{ playbook_dir }}/inventories/templates/group_vars/all-{{ inventory_environment }}.yml"
  when: inventory_environment in ['development', 'staging', 'production']

- name: Load expected environment template
  ansible.builtin.set_fact:
    expected_environment_vars: "{{ lookup('file', expected_template_path) | from_yaml }}"
  when:
    - expected_template_path is defined
    - expected_template_path is file
  failed_when: false

- name: Check package list consistency with template
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [package_drift_msg] }}"
  vars:
    package_drift_msg: "Environment template drift: Current required_rpm_packages differs from {{ inventory_environment }}
      template"
  when:
    - expected_environment_vars is defined
    - required_rpm_packages is defined
    - expected_environment_vars.required_rpm_packages is defined
    - required_rpm_packages | difference(expected_environment_vars.required_rpm_packages) | length > 0

- name: Check service list consistency with template
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [service_drift_msg] }}"
  vars:
    service_drift_msg: "Environment template drift: Current base_services_enabled differs from {{ inventory_environment }}
      template"
  when:
    - expected_environment_vars is defined
    - base_services_enabled is defined
    - expected_environment_vars.base_services_enabled is defined
    - base_services_enabled | difference(expected_environment_vars.base_services_enabled) | length > 0

- name: Check bridge device consistency with template
  ansible.builtin.set_fact:
    configuration_drifts: "{{ configuration_drifts + [bridge_template_drift_msg] }}"
  vars:
    bridge_template_drift_msg: "Environment template drift: Current kvmhost_bridge_device '{{ kvmhost_bridge_device }}' differs
      from {{ inventory_environment }} template '{{ expected_environment_vars.kvmhost_bridge_device }}'"
  when:
    - expected_environment_vars is defined
    - kvmhost_bridge_device is defined
    - expected_environment_vars.kvmhost_bridge_device is defined
    - kvmhost_bridge_device != expected_environment_vars.kvmhost_bridge_device
