---
# KVM Host Network Configuration
# Based on ADR-0007: Network Architecture Decisions

- name: "Network Configuration - Pre-flight Checks"
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - always
    - network_preflight

- name: "Network Configuration - Interface Detection"
  ansible.builtin.include_tasks: interface_detection.yml
  tags:
    - network_detection
    - interface_detection

- name: "Network Configuration - Bridge Setup"
  ansible.builtin.include_tasks: bridge_config.yml
  tags:
    - bridge_config
    - network_bridge

- name: "Network Configuration - Validation"
  ansible.builtin.include_tasks: network_validation.yml
  when: network_validation_enabled
  tags:
    - network_validation
    - validation
