dependency:
  name: galaxy

driver:
  name: podman
  options:
    podman_binary: /usr/bin/podman
    podman_extra_args: --log-level=info

platforms:
  - name: validation-test-rocky9
    image: docker.io/rockylinux/rockylinux:9-ubi-init
    systemd: always
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - rhel9_compatible

  - name: validation-test-rhel9
    image: registry.redhat.io/ubi9/ubi-init:latest
    systemd: always
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - rhel9_compatible

  - name: validation-test-centos9
    image: quay.io/centos/centos:stream9-init
    systemd: always
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - rhel9_compatible

  - name: validation-test-rhel10
    image: registry.redhat.io/ubi10/ubi-init:latest
    systemd: always
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - rhel10_compatible

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: "2"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      host_key_checking: false
      deprecation_warnings: false
    ssh_connection:
      pipelining: true
  playbooks:
    converge: converge.yml
    verify: verify.yml

lint: |
  set -e
  yamllint .
  ansible-lint roles/kvmhost_setup/ --exclude .github/

verifier:
  name: testinfra
  options:
    verbose: true

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
