---
# =============================================================================
# KVMHOST USER CONFIG ROLE - MAIN TASKS
# =============================================================================
# This role configures user shell environments, SSH access, and permissions
# Following ADR-0002: Implement comprehensive validation framework
# Following ADR-0004: Establish modular role architecture

- name: Display kvmhost_user_config role configuration
  ansible.builtin.debug:
    msg:
      - Starting kvmhost_user_config role execution
      - "User config enabled: {{ kvmhost_user_config_enabled }}"
      - "Target user: {{ kvmhost_user_config_target_user }}"
      - "Shell configuration: {{ kvmhost_user_config_shell_enabled }}"
      - "SSH configuration: {{ kvmhost_user_config_ssh_enabled }}"

- name: Validate role dependencies
  ansible.builtin.include_tasks: validation/dependencies.yml
  when: kvmhost_user_config_enabled | bool

- name: Create and configure user accounts
  ansible.builtin.include_tasks: users/account_management.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_create_users | bool

- name: Configure user permissions and groups
  ansible.builtin.include_tasks: users/permissions.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_permissions_enabled | bool

- name: Set up user home directories
  ansible.builtin.include_tasks: home/directory_setup.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_home_setup | bool

- name: Configure shell environment
  ansible.builtin.include_tasks: shell/configuration.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_shell_enabled | bool

- name: Install and configure shell tools
  ansible.builtin.include_tasks: tools/installation.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_tools_enabled | bool

- name: Configure SSH access and keys
  ansible.builtin.include_tasks: ssh/configuration.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_ssh_enabled | bool

- name: Set up dotfiles and configurations
  ansible.builtin.include_tasks: dotfiles/setup.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_dotfiles_enabled | bool

- name: Configure environment variables
  ansible.builtin.include_tasks: environment/variables.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_environment_enabled | bool

- name: Validate user configuration
  ansible.builtin.include_tasks: validation/user_config.yml
  when:
    - kvmhost_user_config_enabled | bool
    - kvmhost_user_config_validation_enabled | bool

- name: Display completion status
  ansible.builtin.debug:
    msg:
      - kvmhost_user_config role execution completed
      - "Configured user: {{ kvmhost_user_config_target_user }}"
      - "Shell: {{ kvmhost_user_config_shell_type }}"
      - "SSH keys generated: {{ kvmhost_user_config_ssh_generate_keys }}"
      - "Groups: {{ kvmhost_user_config_system_groups           | join(', ')   }}"
  when: kvmhost_user_config_enabled | bool
