---
- name: "Idempotency Test Converge - First Run"
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    # Enable testing mode for all roles
    testing_mode: true
    idempotency_test: true
    
    # Override potentially problematic settings for containerized testing
    libvirt_setup_enabled: false  # Skip libvirt in containers
    network_setup_enabled: false  # Skip network configuration in containers
    
  pre_tasks:
    - name: "Update package cache"
      ansible.builtin.package:
        update_cache: true
      changed_when: false
      
    - name: "Install basic testing dependencies"
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - dnf-plugins-core
        state: present

  tasks:
    - name: "Test Role: edge_hosts_validate (validation-only role) - FIRST RUN"
      ansible.builtin.include_role:
        name: edge_hosts_validate
      register: edge_validate_first_run
      tags:
        - edge_hosts_validate
        - validation
      
    - name: "Test Role: swygue_lvm (with mock configuration) - FIRST RUN"
      ansible.builtin.include_role:
        name: swygue_lvm
      register: lvm_first_run
      vars:
        # Mock LVM configuration for container testing
        lvm_testing: true
        skip_lvm_operations: true
      tags:
        - swygue_lvm
        - lvm
      
    - name: "Test Role: kvmhost_setup (partial - container-safe tasks only) - FIRST RUN"
      ansible.builtin.include_role:
        name: kvmhost_setup
        tasks_from: "{{ item }}"
      register: kvmhost_first_run
      loop:
        - configure_shell.yml
        - user_shell_configs.yml
        - build_user_home_dir.yml
        - validate.yml
      vars:
        # Disable hardware/virtualization-specific tasks
        skip_libvirt_setup: true
        skip_network_setup: true
        skip_storage_setup: true
      tags:
        - kvmhost_setup
        - partial

- name: "Idempotency Test Converge - Second Run (Idempotency Check)"
  hosts: all
  become: true
  gather_facts: false
  
  vars:
    # Enable testing mode for all roles
    testing_mode: true
    idempotency_test: true
    
    # Override potentially problematic settings for containerized testing
    libvirt_setup_enabled: false  # Skip libvirt in containers
    network_setup_enabled: false  # Skip network configuration in containers

  tasks:
    - name: "Test Role: edge_hosts_validate (validation-only role) - SECOND RUN"
      ansible.builtin.include_role:
        name: edge_hosts_validate
      register: edge_validate_second_run
      tags:
        - edge_hosts_validate
        - validation
      
    - name: "Test Role: swygue_lvm (with mock configuration) - SECOND RUN"
      ansible.builtin.include_role:
        name: swygue_lvm
      register: lvm_second_run
      vars:
        # Mock LVM configuration for container testing
        lvm_testing: true
        skip_lvm_operations: true
      tags:
        - swygue_lvm
        - lvm
      
    - name: "Test Role: kvmhost_setup (partial - container-safe tasks only) - SECOND RUN"
      ansible.builtin.include_role:
        name: kvmhost_setup
        tasks_from: "{{ item }}"
      register: kvmhost_second_run
      loop:
        - configure_shell.yml
        - user_shell_configs.yml
        - build_user_home_dir.yml
        - validate.yml
      vars:
        # Disable hardware/virtualization-specific tasks
        skip_libvirt_setup: true
        skip_network_setup: true
        skip_storage_setup: true
      tags:
        - kvmhost_setup
        - partial
    
    - name: "Record idempotency test results"
      ansible.builtin.set_fact:
        idempotency_results:
          edge_hosts_validate:
            first_run_changed: "{{ edge_validate_first_run.changed | default(false) }}"
            second_run_changed: "{{ edge_validate_second_run.changed | default(false) }}"
            idempotent: "{{ not (edge_validate_second_run.changed | default(false)) }}"
          swygue_lvm:
            first_run_changed: "{{ lvm_first_run.changed | default(false) }}"
            second_run_changed: "{{ lvm_second_run.changed | default(false) }}"
            idempotent: "{{ not (lvm_second_run.changed | default(false)) }}"
          kvmhost_setup:
            first_run_changed: "{{ kvmhost_first_run.changed | default(false) }}"
            second_run_changed: "{{ kvmhost_second_run.changed | default(false) }}"
            idempotent: "{{ not (kvmhost_second_run.changed | default(false)) }}"
    
    - name: "Display idempotency test summary"
      ansible.builtin.debug:
        msg: |
          Idempotency Test Summary for {{ inventory_hostname }}:
          {% for role_name, result in idempotency_results.items() %}
          - {{ role_name }}: {{ '✅ PASS' if result.idempotent else '❌ FAIL' }}
          {% endfor %}
