- name: Configure user shell environment
  ansible.builtin.ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: bash_profile.j2
      dest: /home/{{ admin_user }}/.bash_profile
    - src: bashrc.j2
      dest: /home/{{ admin_user }}/.bashrc
    - src: vimrc.j2
      dest: /home/{{ admin_user }}/.vimrc
    - src: starship.toml.j2
      dest: /home/{{ admin_user }}/.config/starship.toml
  when: configure_shell | bool

- name: Ensure correct permissions for shell files
  ansible.builtin.ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0644"
  loop:
    - /home/{{ admin_user }}/.bash_profile
    - /home/{{ admin_user }}/.bashrc
    - /home/{{ admin_user }}/.vimrc
    - /home/{{ admin_user }}/.config/starship.toml
  when: configure_shell | bool

- name: Download starship installer
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-install.sh
    mode: "0755"
    owner: root
    group: root

- name: Install starship prompt
  ansible.builtin.command: >
    /tmp/starship-install.sh --yes
  args:
    chdir: /home/{{ admin_user }}
    creates: /usr/local/bin/starship
  when: configure_shell | bool

- name: Add starship to shell configuration
  ansible.builtin.lineinansible.builtin.ansible.builtin.file:
    path: /home/{{ admin_user }}/.bashrc
    regexp: ^eval "\$(starship init bash)"
    line: eval "$(starship init bash)"
    create: true
    mode: "0644"
  when: configure_shell | bool

- name: Verify shell configuration
  ansible.builtin.command: >
    bash -c 'source /home/{{ admin_user }}/.bashrc && echo $SHELL'
  register: shell_check
  changed_when: false
  failed_when: false
  when: configure_shell | bool

- name: Assert shell is properly configured
  ansible.builtin.assert:
    that: shell_check.rc == 0
    fail_msg: Shell configuration failed for user {{ admin_user }}
    success_msg: Shell successfully configured for user {{ admin_user }}
  when: configure_shell | bool
