---
galaxy_info:
  role_name: kvmhost_storage
  author: Qubinode Community
  description: Advanced storage management for KVM hosts including LVM, performance optimization, and monitoring
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "all"
        - "all"
        - "all"
    - name: CentOS
      versions:
        - "all"
    - name: Rocky
      versions:
        - "all"
        - "all"
    - name: AlmaLinux
      versions:
        - "all"
        - "all"
    - name: Fedora
      versions:
        - "37"
        - "38"
        - "39"
        - "40"

  galaxy_tags:
    - storage
    - lvm
    - kvm
    - libvirt
    - filesystem
    - performance
    - monitoring
    - rhel
    - rocky
    - centos

dependencies:
  - role: kvmhost_base
    when: kvmhost_storage_require_base | default(true)
  - role: kvmhost_libvirt
    when: kvmhost_storage_require_libvirt | default(true)

collections:
  - community.general
  - community.libvirt
  - ansible.posix
