---
# =============================================================================
# KVMHOST COCKPIT ROLE - MAIN TASKS
# =============================================================================
# This role configures Cockpit web management interface for KVM hosts
# Following ADR-0002: Implement comprehensive validation framework
# Following ADR-0003: Ensure KVM performance optimization

- name: Display kvmhost_cockpit role configuration
  ansible.builtin.debug:
    msg:
      - Starting kvmhost_cockpit role execution
      - "Cockpit enabled: {{ kvmhost_cockpit_enabled }}"
      - "Port: {{ kvmhost_cockpit_port }}"
      - "SSL enabled: {{ kvmhost_cockpit_ssl_enabled }}"

- name: Validate role dependencies
  ansible.builtin.include_tasks: validation/dependencies.yml
  when: kvmhost_cockpit_enabled | bool

- name: Install Cockpit packages
  ansible.builtin.include_tasks: setup/packages.yml
  when: kvmhost_cockpit_enabled | bool

- name: Configure Cockpit service
  ansible.builtin.include_tasks: configuration/service.yml
  when: kvmhost_cockpit_enabled | bool

- name: Configure Cockpit SSL
  ansible.builtin.include_tasks: configuration/ssl.yml
  when:
    - kvmhost_cockpit_enabled | bool
    - kvmhost_cockpit_ssl_enabled | bool

- name: Configure Cockpit authentication
  ansible.builtin.include_tasks: configuration/authentication.yml
  when: kvmhost_cockpit_enabled | bool

- name: Configure Cockpit firewall
  ansible.builtin.include_tasks: configuration/firewall.yml
  when:
    - kvmhost_cockpit_enabled | bool
    - kvmhost_cockpit_firewall_enabled | bool

- name: Validate Cockpit installation
  ansible.builtin.include_tasks: validation/cockpit.yml
  when: kvmhost_cockpit_enabled | bool

- name: Display completion status
  ansible.builtin.debug:
    msg:
      - kvmhost_cockpit role execution completed
      - >-
        Cockpit web interface available at: {{
        'https' if kvmhost_cockpit_ssl_enabled else 'http' }}://{{
        ansible_default_ipv4.address }}:{{ kvmhost_cockpit_port }}
  when: kvmhost_cockpit_enabled | bool
