# =============================================================================
# KVMHOST COCKPIT ROLE - SERVICE CONFIGURATION
# =============================================================================
# Configures and starts Cockpit service with proper systemd management

- name: Create Cockpit configuration directory
  ansible.builtin.file:
    path: /etc/cockpit
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Configure Cockpit main settings
  ansible.builtin.template:
    src: cockpit.conf.j2
    dest: /etc/cockpit/cockpit.conf
    mode: "0644"
    owner: root
    group: root
    backup: true
  notify: restart cockpit

- name: Configure Cockpit port (if different from default)
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/cockpit.socket.d/listen.conf
    line: ListenStream={{ kvmhost_cockpit_port }}
    regexp: ^ListenStream=
    create: true
    mode: "0644"
    owner: root
    group: root
  when: kvmhost_cockpit_port != 9090
  notify:
    - reload systemd
    - restart cockpit

- name: Create systemd override directory for cockpit.socket
  ansible.builtin.file:
    path: /etc/systemd/system/cockpit.socket.d
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: kvmhost_cockpit_port != 9090

- name: Enable and start cockpit.socket
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: started
    daemon_reload: true

- name: Verify Cockpit socket is active
  ansible.builtin.systemd:
    name: cockpit.socket
  register: cockpit_socket_status

- name: Display Cockpit service status
  ansible.builtin.debug:
    msg:
      - "Cockpit socket status: {{ cockpit_socket_status.status.ActiveState }}"
      - "Cockpit listening on port: {{ kvmhost_cockpit_port }}"
