name: Common Setup

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      ansible-version:
        required: false
        type: string
        default: ''
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
          
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ inputs.python-version }}-
            
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Podman and dependencies
        run: |
          sudo dnf install -y podman slirp4netns podman-docker
          sudo mkdir -p /etc/containers
          echo -e '[registries.search]\nregistries = ["docker.io", "quay.io"]' | sudo tee /etc/containers/registries.conf
          echo -e '[engine]\nevents_logger = "file"\ncgroup_manager = "systemd"' | sudo tee /etc/containers/containers.conf
          sudo systemctl enable --now podman.socket
          
      - name: Install Ansible (if specified)
        if: inputs.ansible-version != ''
        run: |
          pip install ansible-core==${{ inputs.ansible-version }}
